TrialTime: 600 # 10 minutes
OnExpire: MESSAGE # MESSAGE, COMMAND, KICK, or BAN

# Message will only prevent the player from joining once they've disconnected
# Kick will act as a ban, you will need to re-allow them with /trial allow <player>

# If MESSAGE, this will be sent to the player
# If COMMAND, this command will be executed as the server
# If KICK, the player will be kicked with the message
# Placeholders: %player%, %uuid%
Message: 'Your time on this server has expired, please contact the server owner for more information.'